fail_fast: true # makes the hook's pipeline to stop the first time a hook fails
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.4
    hooks:
      - id: commitizen
        stages: 
        - commit-msg
  - repo: local
    hooks:
    - id: lint-fix
      name : lint-fix
      entry: pnpm run lint:fix
      language: system
      pass_filenames: False
      always_run: true
      verbose: True
      stages: 
      - commit
