// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    FlipCard: typeof import('./components/FlipCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GlowingButton: typeof import('./components/GlowingButton.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    NavigationLink: typeof import('./components/NavigationLink.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    TableResponsive: typeof import('./components/TableResponsive.vue')['default']
  }
}

export { }
