// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutAuthoredBooks: typeof import('./components/content/AboutAuthoredBooks.vue')['default']
    AboutEducation: typeof import('./components/content/AboutEducation.vue')['default']
    AboutJobHistory: typeof import('./components/content/AboutJobHistory.vue')['default']
    AboutTechStack: typeof import('./components/content/AboutTechStack.vue')['default']
    AppImage: typeof import('./components/AppImage.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FlipCard: typeof import('./components/FlipCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GlowingButton: typeof import('./components/GlowingButton.vue')['default']
    GlowingHyperLink: typeof import('./components/GlowingHyperLink.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    NavigationLink: typeof import('./components/NavigationLink.vue')['default']
    PortfolioAdversarialPaper: typeof import('./components/content/PortfolioAdversarialPaper.vue')['default']
    PortfolioBoundsPaper: typeof import('./components/content/PortfolioBoundsPaper.vue')['default']
    PortfolioCard: typeof import('./components/PortfolioCard.vue')['default']
    PortfolioDataray: typeof import('./components/content/PortfolioDataray.vue')['default']
    PortfolioPersonalWebsite: typeof import('./components/content/PortfolioPersonalWebsite.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    TableResponsive: typeof import('./components/TableResponsive.vue')['default']
  }
}

export { }
